FROM gcc:latest as build

WORKDIR /test

RUN apt-get update && \
    apt-get install -y \
    git \
    libsfml-dev \
    cmake

ADD ./test /app/test

WORKDIR /app/build

RUN git clone https://github.com/ocornut/imgui.git && \
    git clone https://github.com/SFML/imgui-sfml.git
    
RUN cmake ../test && \
    cmake --build .

FROM ubuntu:latest

WORKDIR /app

COPY --from=build /app/build/manager_app .

ENTRYPOINT ["./launcher_app"]